# Generated by Django 5.0.6 on 2024-12-04 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paper', '0003_alter_question_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longquestions', to='Paper.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.CharField(max_length=1)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='Paper.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='shortQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortquestions', to='Paper.chapter')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
